# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsmain', '0002_auto_20181013_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.CharField(max_length=800),
        ),
    ]
