# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsmain', '0003_auto_20181013_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Welcome Me!', max_length=800),
        ),
    ]
